language: php

php:
  - 5.4
  - 5.5

env:
    - SYMFONY_VERSION=2.4.*

before_script:
    - mysql -e 'drop database if exists powerdns_test;'
    - mysql -e 'create database powerdns_test;'
    - composer self-update
    - composer install -n

script: phpunit --coverage-text