language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
    - SYMFONY_VERSION=2.4.*

before_script:
    - mysql -e 'create database powerdns_test;'
    - composer self-update
    - composer install -n

script: phpunit --coverage-text